apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.appname }}
  name: {{ .Values.appname }}
  labels: 
    group: backend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.appname }}
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 80