apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.appname }}
  name: {{ .Values.appname }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appname }}
                port:
                  name: http